services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3100:3000'
    restart: always
    networks:
      - aurora

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3101:3001'
    env_file:
      - .env
    restart: always
    networks:
      - aurora

networks:
  aurora:
    driver: bridge
